name: Test

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - '*'

jobs:
  test_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run ruby script
        run: ruby ./test.rb
